# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
port: 3000
image:
  repository: bfhlcontainerregistry.azurecr.io/wp-cms
  tag: latest

serviceName: wp-cms
releaseName: wp-cms

namespace: phr
keyVaultName: PHR-AKS-DEV
label: wp-cms
TargetPort: 3000
containerName: wp-cms
containerPort: 3000
ServicePort: 80
name: wp-cms
podName: wp-cms

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  cpu: 1000
  memory: 500
APP:
  PORT: 3000
  APP_ENV: development  
  HRX_SEARCH_BASE_URL: https://bfhldevapigw.healthrx.co.in/hrx-search
  APM_SERVER: http://10.176.144.29:8200

whitelistIp:
  - 52.172.205.59/32
  - 52.172.178.185/32
  - 52.172.185.61/32

resources:
  limits:
    cpu: 1000m
    memory: 762Mi
  requests:
    cpu: 50m
    memory: 64Mi