openapi: 3.0.1
info:
  title: WP - CMS
  version: '1.0'
servers:
  - url: https://dev-api.healthrx.co.in/wp-cms
paths:
  /v1/categories:
    get:
      tags:
        - categories
      summary: get categories
      description: get categories
      operationId: getcategories
      responses:
        '200':
          description: ''
  /v1/categories/{slug}:
    get:
      tags:
        - categories
      summary: get category
      description: get category
      operationId: getcategory
      parameters:
        - name: slug
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /v1/categories/{slug}/posts:
    get:
      tags:
        - categories
      summary: get category posts
      description: get category posts
      operationId: getcategoryposts
      parameters:
        - name: slug
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /v1/web-stories/categories:
    get:
      tags:
        - categories
      summary: get web story categories
      description: get web story categories
      operationId: getwebstorycategories
      responses:
        '200':
          description: ''
  /v1/pages/about-us:
    get:
      tags:
        - pages
      summary: get about us page
      description: get about us page
      operationId: getaboutuspage
      responses:
        '200':
          description: ''
  /v1/pages/{page}:
    get:
      tags:
        - pages
        - lfu
      summary: get page
      description: get page
      operationId: getpage
      parameters:
        - name: page
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /v1/posts:
    get:
      tags:
        - posts
      summary: get posts
      description: get posts
      operationId: getposts
      responses:
        '200':
          description: ''
  /v1/posts/{slug}:
    get:
      tags:
        - posts
      summary: get slug
      description: get slug
      operationId: getslug
      parameters:
        - name: slug
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  # /v1/posts/{slug}/likes:
  #   get:
  #     tags:
  #       - posts
  #     summary: get post likes
  #     description: get post likes
  #     operationId: getpostlikes
  #     parameters:
  #       - name: slug
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: ''
  #   post:
  #     tags:
  #       - posts
  #     summary: create post like
  #     description: create post like
  #     operationId: createpostlike
  #     parameters:
  #       - name: slug
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #     responses:
  #       '201':
  #         description: ''
  #   delete:
  #     tags:
  #       - posts
  #     summary: delete post like
  #     description: delete post like
  #     operationId: deletepostlike
  #     parameters:
  #       - name: slug
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: ''
  # /v1/posts/{slug}/comments:
  #   get:
  #     tags:
  #       - posts
  #     summary: get post comments
  #     description: get post comments
  #     operationId: getpostcomments
  #     parameters:
  #       - name: slug
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: ''
  #   post:
  #     tags:
  #       - posts
  #     summary: create post comment
  #     description: create post comment
  #     operationId: createpostcomment
  #     parameters:
  #       - name: slug
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #     responses:
  #       '201':
  #         description: ''
  # /v1/posts/{slug}/comments/{commentId}:
  #   delete:
  #     tags:
  #       - posts
  #     summary: delete post comment
  #     description: delete post comment
  #     operationId: deletepostcomment
  #     parameters:
  #       - name: slug
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #       - name: commentId
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: ''
  # /v1/posts/{slug}/shares:
  #   get:
  #     tags:
  #       - posts
  #     summary: get post shares
  #     description: get post shares
  #     operationId: getpostshares
  #     parameters:
  #       - name: slug
  #         required: true
  #         in: path
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: ''
  /v1/web-stories/posts/trending:
    get:
      tags:
        - posts
      summary: get trending web stories
      description: get trending web stories
      operationId: gettrendingwebstories
      responses:
        '200':
          description: ''
  /v1/web-stories/posts/{slug}:
    get:
      tags:
        - posts
      summary: get web story
      description: get web story
      operationId: getwebstory
      parameters:
        - name: slug
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /v1/web-stories/posts:
    get:
      tags:
        - posts
      summary: get web stories
      description: get web stories
      operationId: getwebstories
      responses:
        '200':
          description: ''
#  /v1/cache:
#    delete:
#      tags:
#        - app
#      summary: flush the app cache
#      description: flush the app cache
#      operationId: deletecache
#      responses:
#        '200':
#          description: ''
tags:
  - name: health
  - name: categories
  - name: pages
  - name: posts
