apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: "{{ .Values.label }}"
  ports:
    - protocol: TCP
      port: {{ .Values.ServicePort }}
      targetPort: {{ .Values.TargetPort }}
  type: ClusterIP
