{{ if .Values.keyVaultName }}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
    name: "{{ .Values.releaseName }}-sql-db-host"
    namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:  
      type: secret
      name: "{{ .Values.releaseName }}-sql-db-host"
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
    name: "{{ .Values.releaseName }}-sql-db-user"
    namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:  
      type: secret
      name: "{{ .Values.releaseName }}-sql-db-user"
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.releaseName }}-sql-db-password"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:  
      type: secret
      name: "{{ .Values.releaseName }}-sql-db-password"
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.releaseName }}-sql-db-name"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:  
      type: secret
      name: "{{ .Values.releaseName }}-sql-db-name"
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.releaseName }}-shared-count-key"
  namespace: "{{ .Values.namespace }}"
spec:
  vault:
    name: "{{ .Values.keyVaultName }}"
    object:  
      type: secret
      name: "{{ .Values.releaseName }}-shared-count-key"
{{end}}
